// ticket-app-react/src/pages/auth/Login.jsx
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { login } from "../../utils/auth";

// notification instance
const notyf = new Notyf({ duration: 5000 });

const Login = () => {
  // Manage form state
  const [formData, setFormData] = useState({
    email: "",
    password: "",
  });

  const [errors, setErrors] = useState({
    email: "",
    password: "",
  });

  const nav = useNavigate();

  // Handle input change + clear error
  const handleChange = (e) => {
    const { id, value } = e.target;
    setFormData((prev) => ({ ...prev, [id]: value }));
    setErrors((prev) => ({ ...prev, [id]: "" })); // Clear error on type
  };

  // Validation function
  const validate = () => {
    const newErrors = {
      email: "",
      password: "",
    };

    // Email
    if (!formData.email.trim()) {
      newErrors.email = "Email is required";
    }
    // Password: min 4 chars, 1 letter, 1 number
    if (!formData.password) {
      newErrors.password = "Password is required";
    }

    setErrors(newErrors);

    return Object.values(newErrors).every((err) => err === "");
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    if (!validate()) {
      notyf.error("login failed: missing email/password");
      return;
    }
    const loginInfo = login(formData.email, formData.password);
    if (loginInfo.success) {
      notyf.success(loginInfo.message);
      // Reset form
      setFormData({
        email: "",
        password: "",
      });
      setErrors({
        email: "",
        password: "",
      });
      setTimeout(() => {
        nav("/dashboard");
      }, 1500);
    } else {
      // Display an info toast with no title
      notyf.error(loginInfo.message);
    }
  };

  return (
    <main className="w-full bg-[var(--background)] place-content-center text-left grow">
      <form
        id="loginForm"
        noValidate
        onSubmit={handleSubmit}
        className="max-w-md my-4 mx-auto p-6 bg-transparent border-3 border-[var(--secondary)] bg rounded-xl shadow-lg"
      >
        <h2 className="text-2xl font-bold text-center mb-6">Log In</h2>

        <div className="space-y-5 mb-6">
          {/* Email */}
          <div className="form-group">
            <label
              htmlFor="email"
              className="block text-sm font-medium text-[var(--primary-300)] mb-1"
            >
              Email <span className="text-red-500">*</span>
            </label>
            <input
              type="email"
              id="email"
              value={formData.email}
              onChange={handleChange}
              required
              aria-describedby="error-email"
              // data-testid="test-login-email"
              className={`w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[var(--accent)] transition ${
                errors.email
                  ? "border-red-500 focus:ring-red-500"
                  : "border-gray-300"
              }`}
              placeholder="you@example.com"
            />
            <span
              id="error-email"
              // data-testid="test-login-error-email"
              className="error text-red-500 text-sm mt-1 block min-h-5"
              role="alert"
            >
              {errors.email}
            </span>
          </div>

          {/* Password */}
          <div className="form-group">
            <label
              htmlFor="password"
              className="block text-sm font-medium text-[var(--primary-300)] mb-1"
            >
              Password <span className="text-red-500">*</span>
            </label>
            <input
              type="password"
              id="password"
              value={formData.password}
              onChange={handleChange}
              required
              aria-describedby="error-password"
              // data-testid="test-login-password"
              className={`w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[var(--accent)] transition ${
                errors.password
                  ? "border-red-500 focus:ring-red-500"
                  : "border-gray-300"
              }`}
              placeholder="••••••••"
            />
            <span
              id="error-password"
              // data-testid="test-login-error-password"
              className="error text-red-500 text-sm mt-1 block min-h-5"
              role="alert"
            >
              {errors.password}
            </span>
          </div>
        </div>

        {/* Submit Button */}
        <button
          type="submit"
          data-testid="test-login-submit"
          className="w-full btn-2"
        >
          Log in
        </button>

        <p className="text-sm mt-4 text-center">
          Don't have an account?{" "}
          <Link
            to="/auth/signup"
            className="hover:underline font-medium text-nowrap"
          >
            create a new account
          </Link>
        </p>
      </form>
    </main>
  );
};

export default Login;

// ticket-app-vue/src/views/Login.vue
<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { login } from '../utils/auth'
import Footer from '../components/Footer.vue';


// Initialize Notyf
const notyf = new Notyf({ duration: 5000 })

// Router
const router = useRouter()

// Form state
const formData = ref({
    email: '',
    password: ''
})

const errors = ref({
    email: '',
    password: ''
})

// Handle input change + clear error
const handleChange = (field) => (e) => {
    formData.value[field] = e.target.value
    errors.value[field] = '' // Clear error on input
}

// Validation
const validate = () => {
    const newErrors = { email: '', password: '' }

    if (!formData.value.email.trim()) {
        newErrors.email = 'Email is required'
    }

    if (!formData.value.password) {
        newErrors.password = 'Password is required'
    }

    errors.value = newErrors

    return Object.values(newErrors).every(err => err === '')
}

// Submit handler
const handleSubmit = async (e) => {
    e.preventDefault()

    if (!validate()) {
        notyf.error('Login failed: missing email/password')
        return
    }

    const loginInfo = login(formData.value.email, formData.value.password)

    if (loginInfo.success) {
        notyf.success(loginInfo.message)

        // Reset form
        formData.value = { email: '', password: '' }
        errors.value = { email: '', password: '' }

        // Navigate after delay
        setTimeout(() => {
            router.push('/dashboard')
        }, 1500)
    } else {
        notyf.error(loginInfo.message)
    }
}

// Optional: Focus first input on mount
onMounted(() => {
    const emailInput = document.getElementById('email')
    emailInput?.focus()
})
</script>

<template>
    <main class="w-full bg-[var(--background)] place-content-center text-left grow">
        <form id="loginForm" novalidate @submit="handleSubmit"
            class="max-w-md my-4 mx-auto p-6 bg-transparent border-3 border-[var(--secondary)] rounded-xl shadow-lg">
            <h2 class="text-2xl font-bold text-center mb-6">Log In</h2>

            <div class="space-y-5 mb-6">
                <!-- Email -->
                <div class="form-group">
                    <label for="email" class="block text-sm font-medium text-[var(--primary-300)] mb-1">
                        Email <span class="text-red-500">*</span>
                    </label>
                    <input type="email" id="email" v-model="formData.email" @input="handleChange('email')" required
                        aria-describedby="error-email"
                        class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[var(--accent)] transition"
                        :class="{
                            'border-red-500 focus:ring-red-500': errors.email,
                            'border-gray-300': !errors.email
                        }" placeholder="you@example.com" />
                    <span id="error-email" class="error text-red-500 text-sm mt-1 block min-h-5" role="alert">
                        {{ errors.email }}
                    </span>
                </div>

                <!-- Password -->
                <div class="form-group">
                    <label for="password" class="block text-sm font-medium text-[var(--primary-300)] mb-1">
                        Password <span class="text-red-500">*</span>
                    </label>
                    <input type="password" id="password" v-model="formData.password" @input="handleChange('password')"
                        required aria-describedby="error-password"
                        class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[var(--accent)] transition"
                        :class="{
                            'border-red-500 focus:ring-red-500': errors.password,
                            'border-gray-300': !errors.password
                        }" placeholder="••••••••" />
                    <span id="error-password" class="error text-red-500 text-sm mt-1 block min-h-5" role="alert">
                        {{ errors.password }}
                    </span>
                </div>
            </div>

            <!-- Submit Button -->
            <button type="submit" class="w-full btn-2">
                Log in
            </button>

            <p class="text-sm mt-4 text-center">
                Don't have an account?

                <RouterLink to="/auth/signup"> create a new account
                </RouterLink>
            </p>
        </form>
    </main>
    <Footer/>
</template>
